// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMl2tDbC7HPwDdYH1F5uwBrO-_edcjpIs',
    appId: '1:988160166393:web:c7c64dbe1e9628e7e45528',
    messagingSenderId: '988160166393',
    projectId: 'me-mpr',
    authDomain: 'me-mpr.firebaseapp.com',
    storageBucket: 'me-mpr.firebasestorage.app',
    measurementId: 'G-TQE039E9Z2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhmi9PnZwHAQN8xB-Wb_1KSzazEBsDENk',
    appId: '1:988160166393:android:55e21425ed40af27e45528',
    messagingSenderId: '988160166393',
    projectId: 'me-mpr',
    storageBucket: 'me-mpr.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDw3gSp9q48UvpWs-oiTTAVXpOdt_8wUHc',
    appId: '1:988160166393:ios:a9145b2db8a18e56e45528',
    messagingSenderId: '988160166393',
    projectId: 'me-mpr',
    storageBucket: 'me-mpr.firebasestorage.app',
    androidClientId: '988160166393-60lg68kqhgc1eblfiqfote8sqgumsfr7.apps.googleusercontent.com',
    iosClientId: '988160166393-e3aebt97bm6lv3giguo1iaktfm393d9g.apps.googleusercontent.com',
    iosBundleId: 'com.example.meMpr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDw3gSp9q48UvpWs-oiTTAVXpOdt_8wUHc',
    appId: '1:988160166393:ios:a9145b2db8a18e56e45528',
    messagingSenderId: '988160166393',
    projectId: 'me-mpr',
    storageBucket: 'me-mpr.firebasestorage.app',
    androidClientId: '988160166393-60lg68kqhgc1eblfiqfote8sqgumsfr7.apps.googleusercontent.com',
    iosClientId: '988160166393-e3aebt97bm6lv3giguo1iaktfm393d9g.apps.googleusercontent.com',
    iosBundleId: 'com.example.meMpr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMl2tDbC7HPwDdYH1F5uwBrO-_edcjpIs',
    appId: '1:988160166393:web:02db0ec61f991fbee45528',
    messagingSenderId: '988160166393',
    projectId: 'me-mpr',
    authDomain: 'me-mpr.firebaseapp.com',
    storageBucket: 'me-mpr.firebasestorage.app',
    measurementId: 'G-VP3XQT1SEL',
  );
}
